[[UNRESOLVED_MEMBER]]
id = "CODEWARE_10900"
span_starts_with = "scrollArea.useInternalMask"
message = "Install Codeware 1.9.0 or higher"

[[UNRESOLVED_MEMBER]]
id = "CODEWARE_10900"
span_starts_with = "scrollController.ScrollArea"
message = "Install Codeware 1.9.0 or higher"
